Disambiguate logback Logger
  - Fixes an issue with abiguous usage of Logger in sbt plugin (`Logger` class is
  defined in both `sbt.Logger` and `ch.qos.logback.classic`).
  - It caused an error when trying to set a custom log level via system
  properties, since `sbt.Logger` does not implement `setLevel`.

```scala
scala> import ch.qos.logback.classic.{Logger, Level}
scala> import sbt._
scala>           LoggerFactory.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME).asInstanceOf[Logger].setLevel(
     |             Level.toLevel(System.getProperty("pact.logLevel"))
     |           )
<console>:24: error: reference to Logger is ambiguous;
it is imported twice in the same scope by
import sbt._
and import ch.qos.logback.classic.{Logger, Level}
                 LoggerFactory.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME).asInstanceOf[Logger].setLevel(
```